# Generated by Django 4.0.5 on 2022-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[(None, 'Choose..'), ('small', 'Small'), ('Medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('sauce', models.CharField(choices=[('Ketchup', 'Ketchup'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Chilli Sauce', 'Chilli Sauce'), ('Paprika Sauce', 'Paprika Sauce')], max_length=50)),
                ('pizza', models.CharField(choices=[('neapolitan', 'Neapolitan'), ('Assorted', 'Assorted'), ('Vegetarian', 'Vegetarian'), ('Margarita', 'Margarita')], max_length=50)),
            ],
        ),
    ]
